### ISSUE TITLE
Cant fund  X Chain addresses anymore

### ISSUE THREAD

**Issue by parthwaidya** [ava-labs/avalanche-faucet#16]
Have you removed the feature of funding X chain wallets?
There's just a C chain address option now.

**Comment by rajranjan0608** [comment]
We will restart the X-Chain faucet drops soon. For now, you can use the cross-chain transfer on [Avalanche Wallet](https://wallet.avax.network) to transfer the funds from C-Chain to X-Chain. For more details on cross-chain transfers, please refer to this support [ticket](https://support.avax.network/en/articles/6169872-how-to-make-a-cross-chain-transfer-in-the-avalanche-wallet).
