### ISSUE TITLE
Adding ERC20 tokens to fuji faucet

### ISSUE THREAD

**Issue by 0xju1ie** [ava-labs/avalanche-faucet#39]
Hello,

I see that there is the option to make a PR to add a subnet to the faucet.

Wondering if the team is allowing people to add to the ERC20 coin options for the fuji c-chain?

**Comment by rajranjan0608** [comment]
Yes. You can make a PR for adding ERC20 tokens for chains (or subnets) that are already listed on the faucet.

**Comment by muhyomoto** [comment]
The faucet WAVAX balance is 1 .   how do I increase it? 
thanks

**Comment by talhaakkaya** [comment]
> The faucet WAVAX balance is 1 . how do I increase it? thanks

It increases when someone sends WAVAX to 0x2352D20fC81225c8ECD8f6FaA1B37F24FEd450c9 which is referred bottom of the page.
