### ISSUE TITLE
WAGMI faucet runs out of token

### ISSUE THREAD

**Issue by anhskrttt** [ava-labs/avalanche-faucet#67]
Hi all,

I wanna faucet some WGM tokens from the faucet, but it seems like the WAGMI faucet is drained (the faucet balance is "1 WGM"). I'm not sure if this problem will be solved soon? Where else can I get some WGM tokens?

Thanks.

![image](https://user-images.githubusercontent.com/41201391/199423831-2dbf64eb-13fe-43ca-a5f2-18faf23483a0.png)

**Comment by rajranjan0608** [comment]
Refueled 🚀
