### ISSUE TITLE
Token disapeared after a swap

### ISSUE THREAD

**Issue by katzs500** [ava-labs/avalanche-faucet#74]
After a swap to BSC or any other testnet network, and checking for the tokens , there are missing, see screenshots.

![2022-11-20_17h42_26](https://user-images.githubusercontent.com/104980430/202911557-a3560f66-1969-48c8-828e-b2e5393d0dd1.png)

![2022-11-20_17h41_15](https://user-images.githubusercontent.com/104980430/202911569-c110f7ab-a032-45b1-bacc-21f0b8b8351c.png)
![2022-11-20_17h41_05](https://user-images.githubusercontent.com/104980430/202911574-7c1b3d5c-8a1a-4897-a42d-c01c97830af3.png)

**Comment by nahoc** [comment]
Again, not related to this project whatsoever.
